version: '3.4'


services:
  app:
    image: bg-tasks
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data/logs:/app/logs
    container_name: ${APP_NAME}-app
    ports:
        - ${APP_PORT}:5000
    depends_on:
      - redis
    networks:
      - backend
      - frontend

  worker:
    image: bg-tasks
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data/logs:/app/logs
    container_name: ${APP_NAME}-worker
    depends_on:
      - redis
      - app
    networks:
      - backend
    entrypoint: ['/app/src/start_worker.sh']

  scheduler:
    image: bg-tasks
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data/logs:/app/logs
    container_name: ${APP_NAME}-scheduler
    depends_on:
      - redis
      - app
    networks:
      - backend
    entrypoint: ['/app/src/start_scheduler.sh']

  redis:
    image: redis:latest
    container_name: ${APP_NAME}-redis
    restart: always
    networks:
      - backend
    volumes:
      - ./data/redis:/app_data/redis

networks:
  frontend:
  backend: